"""
업종별 AI 프롬프트 및 설정 관리
"""

from enum import Enum
from typing import Dict, Any, List
from app.models.user import IndustryType


# 업종별 기본 설정
INDUSTRY_CONFIGS: Dict[IndustryType, Dict[str, Any]] = {
    IndustryType.MEDICAL: {
        "name": "의료",
        "name_en": "Medical",
        "icon": "🏥",
        "business_name_label": "병원/의원명",
        "specialty_label": "진료과목",
        "specialty_options": [
            "내과", "외과", "정형외과", "신경외과", "산부인과", "소아청소년과",
            "피부과", "안과", "이비인후과", "비뇨의학과", "정신건강의학과",
            "재활의학과", "가정의학과", "영상의학과", "마취통증의학과",
            "성형외과", "치과", "한의원", "종합병원", "기타"
        ],
        "tone": "전문적이고 신뢰감 있는",
        "cta_options": ["예약 상담", "진료 예약", "온라인 상담", "카카오톡 상담"],
        "keywords_hint": "증상, 질환명, 시술명 등",
        "compliance_warning": "의료법에 따라 과대광고, 비교광고가 금지됩니다.",
        "ai_system_prompt": """당신은 의료 마케팅 전문 블로그 작성자입니다.
의료법 광고규제를 준수하면서 전문적이고 신뢰감 있는 톤으로 글을 작성합니다.
- 과대광고, 비교광고 금지
- 의학적 효과를 단정적으로 표현하지 않음
- 환자 후기는 객관적으로 서술
- 전문 의료 용어와 일반인이 이해하기 쉬운 설명을 병행""",
        "sample_topics": [
            "진료 안내",
            "건강 정보",
            "시술/수술 소개",
            "의료진 소개",
            "병원 소식"
        ]
    },

    IndustryType.LEGAL: {
        "name": "법률",
        "name_en": "Legal",
        "icon": "⚖️",
        "business_name_label": "법률사무소명",
        "specialty_label": "전문분야",
        "specialty_options": [
            "민사소송", "형사소송", "이혼/가사", "상속", "부동산",
            "기업법무", "노동법", "의료소송", "교통사고", "성범죄",
            "지식재산권", "파산/회생", "행정소송", "세무", "기타"
        ],
        "tone": "신뢰성 있고 전문적인",
        "cta_options": ["무료 상담", "법률 상담 예약", "카카오톡 상담", "전화 상담"],
        "keywords_hint": "법률 분야, 사건 유형, 지역명 등",
        "compliance_warning": "변호사 광고규정에 따라 품위유지, 과대광고 금지가 적용됩니다.",
        "ai_system_prompt": """당신은 법률 마케팅 전문 블로그 작성자입니다.
변호사 광고규정을 준수하면서 신뢰성 있고 전문적인 톤으로 글을 작성합니다.
- 승소율, 성공사례 과장 금지
- 법률 정보는 일반적인 안내로 작성
- 개별 사안에 따라 결과가 다를 수 있음을 명시
- 전문 법률 용어와 쉬운 설명을 병행
- 독자가 전문가 상담의 필요성을 느끼도록 작성""",
        "sample_topics": [
            "법률 상식",
            "판례 해설",
            "분야별 법률 가이드",
            "상담 사례 (익명)",
            "법률 뉴스 해설"
        ]
    },

    IndustryType.RESTAURANT: {
        "name": "음식점/카페",
        "name_en": "Restaurant",
        "icon": "🍽️",
        "business_name_label": "상호명",
        "specialty_label": "업종",
        "specialty_options": [
            "한식", "중식", "일식", "양식", "분식", "치킨/피자",
            "카페/디저트", "베이커리", "술집/바", "뷔페", "기타"
        ],
        "tone": "친근하고 맛있어 보이는",
        "cta_options": ["예약하기", "배달 주문", "방문하기", "쿠폰 받기"],
        "keywords_hint": "지역명, 음식 종류, 분위기 키워드 등",
        "compliance_warning": "표시광고법에 따라 허위/과장 광고가 금지됩니다.",
        "ai_system_prompt": """당신은 맛집/카페 마케팅 전문 블로그 작성자입니다.
친근하고 생동감 있는 톤으로 음식과 매장의 매력을 전달합니다.
- 음식의 맛, 식감, 향을 구체적으로 묘사
- 인스타그래머블한 포인트 강조
- 위치, 주차, 영업시간 등 실용 정보 포함
- 가격 대비 만족도, 추천 메뉴 제안
- 방문 욕구를 자극하는 생생한 후기 스타일""",
        "sample_topics": [
            "메뉴 소개",
            "신메뉴 출시",
            "매장 분위기",
            "이벤트/프로모션",
            "고객 후기"
        ]
    },

    IndustryType.BEAUTY: {
        "name": "미용/뷰티",
        "name_en": "Beauty",
        "icon": "💇",
        "business_name_label": "상호명",
        "specialty_label": "업종",
        "specialty_options": [
            "헤어샵", "네일샵", "피부관리", "속눈썹", "왁싱",
            "메이크업", "타투", "반영구", "종합뷰티샵", "기타"
        ],
        "tone": "트렌디하고 세련된",
        "cta_options": ["예약하기", "카카오톡 상담", "가격 문의", "포트폴리오 보기"],
        "keywords_hint": "시술명, 스타일, 지역명 등",
        "compliance_warning": "표시광고법에 따라 시술 효과 과장이 금지됩니다.",
        "ai_system_prompt": """당신은 뷰티 마케팅 전문 블로그 작성자입니다.
트렌디하고 세련된 톤으로 뷰티 서비스의 매력을 전달합니다.
- 최신 트렌드와 스타일 반영
- 시술 과정과 결과를 상세히 설명
- 비포/애프터 효과 자연스럽게 전달
- 개인 맞춤 상담의 중요성 강조
- 인스타그래머블한 감성적 표현 사용""",
        "sample_topics": [
            "시술 소개",
            "트렌드 스타일",
            "비포/애프터",
            "디자이너 소개",
            "이벤트/할인"
        ]
    },

    IndustryType.FITNESS: {
        "name": "피트니스",
        "name_en": "Fitness",
        "icon": "💪",
        "business_name_label": "센터명",
        "specialty_label": "운동종류",
        "specialty_options": [
            "헬스장", "필라테스", "요가", "크로스핏", "PT전문",
            "수영장", "골프연습장", "댄스", "복싱/격투기", "기타"
        ],
        "tone": "활기차고 동기부여하는",
        "cta_options": ["무료 체험", "상담 예약", "등록 문의", "프로그램 보기"],
        "keywords_hint": "운동 종류, 목적(다이어트/근력), 지역명 등",
        "compliance_warning": "건강기능식품 광고와 구분하여 작성해야 합니다.",
        "ai_system_prompt": """당신은 피트니스 마케팅 전문 블로그 작성자입니다.
활기차고 동기부여가 되는 톤으로 운동의 가치를 전달합니다.
- 운동 효과와 건강상 이점 설명
- 프로그램과 시설 특징 강조
- 초보자도 시작할 수 있다는 메시지 전달
- 트레이너의 전문성 어필
- 목표 달성 스토리와 동기부여 콘텐츠""",
        "sample_topics": [
            "프로그램 소개",
            "운동 가이드",
            "회원 후기",
            "트레이너 소개",
            "시설 안내"
        ]
    },

    IndustryType.EDUCATION: {
        "name": "교육/학원",
        "name_en": "Education",
        "icon": "📚",
        "business_name_label": "학원명",
        "specialty_label": "과목/분야",
        "specialty_options": [
            "입시(국영수)", "영어전문", "수학전문", "코딩/IT", "예체능",
            "유아/초등", "중등", "고등", "성인교육", "자격증", "기타"
        ],
        "tone": "신뢰감 있고 성과 중심의",
        "cta_options": ["무료 상담", "레벨테스트", "체험수업", "커리큘럼 문의"],
        "keywords_hint": "과목, 대상(초등/중등/고등), 지역명 등",
        "compliance_warning": "학원법에 따라 허위 합격실적 광고가 금지됩니다.",
        "ai_system_prompt": """당신은 교육 마케팅 전문 블로그 작성자입니다.
신뢰감 있고 성과 중심의 톤으로 교육 서비스의 가치를 전달합니다.
- 커리큘럼과 교육 방법론 설명
- 강사진의 전문성 강조
- 학습 성과와 후기 공유
- 학부모/학생 관점의 실질적 정보
- 상담을 통한 맞춤 학습 설계 유도""",
        "sample_topics": [
            "커리큘럼 소개",
            "학습법 가이드",
            "성적향상 사례",
            "강사 소개",
            "학원 소식"
        ]
    },

    IndustryType.REALESTATE: {
        "name": "부동산",
        "name_en": "Real Estate",
        "icon": "🏠",
        "business_name_label": "중개사무소명",
        "specialty_label": "전문분야",
        "specialty_options": [
            "아파트", "오피스텔", "상가", "사무실", "토지",
            "빌딩", "공장/창고", "원룸/투룸", "전원주택", "기타"
        ],
        "tone": "전문적이고 신뢰감 있는",
        "cta_options": ["매물 문의", "상담 예약", "시세 조회", "방문 예약"],
        "keywords_hint": "지역명, 매물 유형, 특징 등",
        "compliance_warning": "공인중개사법에 따라 허위매물 광고가 금지됩니다.",
        "ai_system_prompt": """당신은 부동산 마케팅 전문 블로그 작성자입니다.
전문적이고 신뢰감 있는 톤으로 부동산 정보를 전달합니다.
- 매물의 장점과 특징을 객관적으로 설명
- 입지, 교통, 학군 등 실질적 정보 제공
- 시세 동향과 투자 가치 분석
- 지역 개발 호재 정보 공유
- 전문 중개사로서의 신뢰감 전달""",
        "sample_topics": [
            "매물 소개",
            "지역 분석",
            "시세 동향",
            "부동산 상식",
            "투자 가이드"
        ]
    },

    IndustryType.OTHER: {
        "name": "기타 자영업",
        "name_en": "Other Business",
        "icon": "🏪",
        "business_name_label": "상호명",
        "specialty_label": "업종",
        "specialty_options": [
            "소매점", "서비스업", "제조업", "온라인쇼핑몰", "프랜차이즈", "기타"
        ],
        "tone": "친근하고 신뢰감 있는",
        "cta_options": ["문의하기", "방문 예약", "상담 신청", "견적 요청"],
        "keywords_hint": "업종, 서비스, 지역명 등",
        "compliance_warning": "표시광고법에 따라 허위/과장 광고가 금지됩니다.",
        "ai_system_prompt": """당신은 소상공인 마케팅 전문 블로그 작성자입니다.
친근하고 신뢰감 있는 톤으로 비즈니스의 가치를 전달합니다.
- 제품/서비스의 특징과 장점 설명
- 고객 후기와 사례 공유
- 업체의 전문성과 차별점 강조
- 접근성 좋은 정보 제공
- 고객과의 신뢰 관계 구축""",
        "sample_topics": [
            "서비스 소개",
            "고객 후기",
            "이벤트/프로모션",
            "업체 소개",
            "업계 정보"
        ]
    }
}


def get_industry_config(industry_type: IndustryType) -> Dict[str, Any]:
    """업종별 설정 반환"""
    return INDUSTRY_CONFIGS.get(industry_type, INDUSTRY_CONFIGS[IndustryType.OTHER])


def get_industry_ai_prompt(industry_type: IndustryType, base_prompt: str = "") -> str:
    """업종별 AI 시스템 프롬프트 생성"""
    config = get_industry_config(industry_type)
    system_prompt = config.get("ai_system_prompt", "")

    if base_prompt:
        return f"{system_prompt}\n\n{base_prompt}"
    return system_prompt


def get_all_industries() -> List[Dict[str, Any]]:
    """모든 업종 목록 반환 (프론트엔드용)"""
    return [
        {
            "value": industry.value,
            "name": config["name"],
            "name_en": config["name_en"],
            "icon": config["icon"],
            "business_name_label": config["business_name_label"],
            "specialty_label": config["specialty_label"],
            "specialty_options": config["specialty_options"],
            "sample_topics": config["sample_topics"],
            "template_count": len(INDUSTRY_WRITING_TEMPLATES.get(industry, [])),
        }
        for industry, config in INDUSTRY_CONFIGS.items()
    ]


# ==================== 업종별 글쓰기 템플릿 ====================

INDUSTRY_WRITING_TEMPLATES: Dict[IndustryType, List[Dict[str, Any]]] = {
    IndustryType.MEDICAL: [
        {
            "id": "medical_procedure",
            "name": "시술/수술 소개",
            "icon": "💉",
            "description": "시술이나 수술 과정을 전문적으로 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 2000,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 7,
                "friendliness": 5,
                "technical_depth": 7,
                "storytelling": 4,
                "emotion": 3,
                "humor": 2,
                "question_usage": 4,
                "metaphor_usage": 3,
                "sentence_length": 6,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "시술/수술명, 적응증, 시술 과정, 회복 기간, 주의사항 등을 입력하세요",
            "example_topics": ["라식 수술 안내", "보톡스 시술 과정", "무릎 인공관절 수술"],
        },
        {
            "id": "medical_health_info",
            "name": "건강 정보",
            "icon": "📋",
            "description": "질환이나 건강 관련 유용한 정보를 제공하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 6,
                "storytelling": 5,
                "emotion": 4,
                "humor": 2,
                "question_usage": 6,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": True,
                "search_intent_match": True,
            },
            "placeholder_content": "질환명, 증상, 원인, 예방법, 치료 방법 등을 입력하세요",
            "example_topics": ["당뇨병 초기 증상", "허리디스크 예방법", "고혈압 관리 가이드"],
        },
        {
            "id": "medical_patient_review",
            "name": "환자 후기",
            "icon": "💬",
            "description": "치료 경험을 공유하는 환자 후기 스타일의 글",
            "config": {
                "persuasion_level": 5,
                "framework": "공감해결형",
                "target_length": 1500,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 4,
                "friendliness": 8,
                "technical_depth": 4,
                "storytelling": 9,
                "emotion": 8,
                "humor": 3,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "방문 계기, 치료 과정, 결과, 느낀 점 등을 입력하세요",
            "example_topics": ["치과 임플란트 후기", "도수치료 3개월 경험", "피부과 여드름 치료기"],
        },
        {
            "id": "medical_doctor_intro",
            "name": "의료진 소개",
            "icon": "👨‍⚕️",
            "description": "의료진의 전문성과 경력을 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 1500,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 7,
                "friendliness": 5,
                "technical_depth": 6,
                "storytelling": 6,
                "emotion": 4,
                "humor": 2,
                "question_usage": 3,
                "metaphor_usage": 3,
                "sentence_length": 6,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "의료진 이름, 전문 분야, 학력, 경력, 진료 철학 등을 입력하세요",
            "example_topics": ["정형외과 전문의 소개", "한의원 원장 프로필", "피부과 대표원장 소개"],
        },
        {
            "id": "medical_hospital_news",
            "name": "병원 소식",
            "icon": "🏥",
            "description": "병원의 새로운 소식이나 이벤트를 알리는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "관심유도형",
                "target_length": 1200,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 4,
                "storytelling": 5,
                "emotion": 5,
                "humor": 4,
                "question_usage": 4,
                "metaphor_usage": 3,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": False,
                "experience_focus": False,
                "expertise": False,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": False,
            },
            "placeholder_content": "소식 내용, 기간, 대상, 혜택 등을 입력하세요",
            "example_topics": ["진료시간 변경 안내", "새 장비 도입 소식", "건강검진 이벤트"],
        },
    ],

    IndustryType.LEGAL: [
        {
            "id": "legal_knowledge",
            "name": "법률 상식",
            "icon": "📖",
            "description": "일반인이 알아두면 좋은 법률 상식을 쉽게 설명하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 2000,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 6,
                "storytelling": 5,
                "emotion": 3,
                "humor": 3,
                "question_usage": 7,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": True,
                "search_intent_match": True,
            },
            "placeholder_content": "법률 주제, 관련 법조항, 사례 등을 입력하세요",
            "example_topics": ["전세 사기 예방법", "교통사고 과실 비율", "상속 순위 총정리"],
        },
        {
            "id": "legal_case_study",
            "name": "판례 해설",
            "icon": "⚖️",
            "description": "실제 판례를 쉽게 풀어서 해설하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 2200,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 7,
                "friendliness": 5,
                "technical_depth": 8,
                "storytelling": 6,
                "emotion": 3,
                "humor": 2,
                "question_usage": 5,
                "metaphor_usage": 4,
                "sentence_length": 6,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": True,
                "search_intent_match": True,
            },
            "placeholder_content": "판례 번호, 사건 개요, 판결 요지, 의미 등을 입력하세요",
            "example_topics": ["부당해고 판례 분석", "명예훼손 무죄 판결 해설", "임대차 분쟁 판례"],
        },
        {
            "id": "legal_consultation",
            "name": "상담 사례",
            "icon": "💬",
            "description": "익명화된 상담 사례를 통해 법률 지식을 전달하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "공감해결형",
                "target_length": 1800,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 7,
                "technical_depth": 6,
                "storytelling": 8,
                "emotion": 5,
                "humor": 2,
                "question_usage": 6,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "상담 배경, 의뢰인 상황(익명), 법적 쟁점, 해결 방향 등을 입력하세요",
            "example_topics": ["이혼 재산분할 상담 사례", "산재 인정 사례", "채권 추심 상담"],
        },
        {
            "id": "legal_guide",
            "name": "법률 가이드",
            "icon": "📝",
            "description": "특정 법률 절차를 단계별로 안내하는 가이드 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 2000,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 7,
                "storytelling": 4,
                "emotion": 3,
                "humor": 2,
                "question_usage": 5,
                "metaphor_usage": 3,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "절차명, 필요 서류, 단계별 진행 방법, 비용, 기간 등을 입력하세요",
            "example_topics": ["소액소송 절차 가이드", "개인회생 신청 방법", "내용증명 작성법"],
        },
    ],

    IndustryType.RESTAURANT: [
        {
            "id": "restaurant_menu",
            "name": "메뉴 소개",
            "icon": "🍳",
            "description": "대표 메뉴나 인기 메뉴를 맛있게 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "관심유도형",
                "target_length": 1500,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 4,
                "friendliness": 8,
                "technical_depth": 4,
                "storytelling": 7,
                "emotion": 7,
                "humor": 5,
                "question_usage": 5,
                "metaphor_usage": 7,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "메뉴명, 재료, 맛 특징, 가격, 추천 포인트 등을 입력하세요",
            "example_topics": ["시그니처 파스타 소개", "계절 한정 메뉴", "런치 세트 추천"],
        },
        {
            "id": "restaurant_new_menu",
            "name": "신메뉴 출시",
            "icon": "🆕",
            "description": "새로 출시한 메뉴를 홍보하는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "관심유도형",
                "target_length": 1200,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 3,
                "friendliness": 9,
                "technical_depth": 3,
                "storytelling": 7,
                "emotion": 8,
                "humor": 6,
                "question_usage": 6,
                "metaphor_usage": 7,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "신메뉴명, 개발 스토리, 맛 포인트, 출시일, 가격 등을 입력하세요",
            "example_topics": ["봄 시즌 딸기 디저트", "신메뉴 매운 떡볶이", "콜라보 한정 메뉴"],
        },
        {
            "id": "restaurant_atmosphere",
            "name": "매장 분위기",
            "icon": "✨",
            "description": "매장의 인테리어와 분위기를 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "관심유도형",
                "target_length": 1200,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 3,
                "friendliness": 8,
                "technical_depth": 3,
                "storytelling": 8,
                "emotion": 8,
                "humor": 5,
                "question_usage": 4,
                "metaphor_usage": 8,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "인테리어 컨셉, 좌석 배치, 포토존, 주차 정보 등을 입력하세요",
            "example_topics": ["루프탑 테라스 소개", "프라이빗 룸 안내", "인스타 감성 인테리어"],
        },
        {
            "id": "restaurant_event",
            "name": "이벤트/프로모션",
            "icon": "🎉",
            "description": "할인, 이벤트, 프로모션을 홍보하는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "관심유도형",
                "target_length": 1000,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 3,
                "friendliness": 9,
                "technical_depth": 2,
                "storytelling": 5,
                "emotion": 7,
                "humor": 6,
                "question_usage": 6,
                "metaphor_usage": 5,
                "sentence_length": 3,
            },
            "seo_optimization": {
                "enabled": False,
                "experience_focus": False,
                "expertise": False,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": False,
            },
            "placeholder_content": "이벤트명, 기간, 할인 내용, 참여 방법, 혜택 등을 입력하세요",
            "example_topics": ["오픈 기념 50% 할인", "생일 고객 무료 케이크", "SNS 리뷰 이벤트"],
        },
    ],

    IndustryType.BEAUTY: [
        {
            "id": "beauty_procedure",
            "name": "시술 소개",
            "icon": "💆",
            "description": "뷰티 시술의 과정과 효과를 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 6,
                "storytelling": 6,
                "emotion": 5,
                "humor": 3,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "시술명, 효과, 시술 시간, 회복 기간, 가격대 등을 입력하세요",
            "example_topics": ["물광 주사 효과", "두피 케어 프로그램", "네일 아트 트렌드"],
        },
        {
            "id": "beauty_trend",
            "name": "트렌드 스타일",
            "icon": "💅",
            "description": "최신 뷰티 트렌드와 스타일을 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "관심유도형",
                "target_length": 1500,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 4,
                "friendliness": 8,
                "technical_depth": 5,
                "storytelling": 6,
                "emotion": 7,
                "humor": 5,
                "question_usage": 6,
                "metaphor_usage": 7,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "트렌드명, 스타일 특징, 추천 대상, 관리 방법 등을 입력하세요",
            "example_topics": ["올해 봄 헤어 트렌드", "글로우 메이크업", "젤네일 디자인 모음"],
        },
        {
            "id": "beauty_before_after",
            "name": "비포/애프터",
            "icon": "🔄",
            "description": "시술 전후 변화를 보여주는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "공감해결형",
                "target_length": 1500,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 4,
                "friendliness": 8,
                "technical_depth": 5,
                "storytelling": 9,
                "emotion": 8,
                "humor": 3,
                "question_usage": 5,
                "metaphor_usage": 6,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "시술 전 고민, 시술 과정, 시술 후 변화, 만족도 등을 입력하세요",
            "example_topics": ["탈모 치료 6개월 변화", "피부 관리 비포애프터", "헤어 염색 변신"],
        },
        {
            "id": "beauty_event",
            "name": "이벤트",
            "icon": "🎁",
            "description": "뷰티샵 이벤트나 할인 소식을 알리는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "관심유도형",
                "target_length": 1000,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 3,
                "friendliness": 9,
                "technical_depth": 3,
                "storytelling": 5,
                "emotion": 7,
                "humor": 5,
                "question_usage": 6,
                "metaphor_usage": 5,
                "sentence_length": 3,
            },
            "seo_optimization": {
                "enabled": False,
                "experience_focus": False,
                "expertise": False,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": False,
            },
            "placeholder_content": "이벤트명, 기간, 할인 내용, 대상 시술, 예약 방법 등을 입력하세요",
            "example_topics": ["봄맞이 피부관리 할인", "신규 고객 50% 할인", "친구 추천 이벤트"],
        },
    ],

    IndustryType.FITNESS: [
        {
            "id": "fitness_program",
            "name": "프로그램 소개",
            "icon": "🏋️",
            "description": "운동 프로그램을 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 6,
                "storytelling": 6,
                "emotion": 5,
                "humor": 4,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "프로그램명, 대상, 운동 구성, 효과, 기간, 가격 등을 입력하세요",
            "example_topics": ["PT 프로그램 소개", "다이어트 캠프", "시니어 건강 운동"],
        },
        {
            "id": "fitness_exercise_guide",
            "name": "운동 가이드",
            "icon": "📋",
            "description": "운동 방법과 자세를 안내하는 가이드 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 7,
                "storytelling": 4,
                "emotion": 4,
                "humor": 4,
                "question_usage": 5,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "운동명, 자세, 세트/횟수, 주의사항, 효과 등을 입력하세요",
            "example_topics": ["홈트레이닝 루틴", "스쿼트 올바른 자세", "코어 강화 운동법"],
        },
        {
            "id": "fitness_member_review",
            "name": "회원 후기",
            "icon": "⭐",
            "description": "회원의 운동 성과와 후기를 공유하는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "공감해결형",
                "target_length": 1500,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 4,
                "friendliness": 8,
                "technical_depth": 4,
                "storytelling": 9,
                "emotion": 8,
                "humor": 4,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "등록 계기, 운동 과정, 체중/체형 변화, 느낀 점 등을 입력하세요",
            "example_topics": ["-15kg 다이어트 성공기", "근력 운동 3개월 변화", "요가로 허리통증 극복"],
        },
        {
            "id": "fitness_facility",
            "name": "시설 안내",
            "icon": "🏢",
            "description": "센터 시설과 장비를 소개하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 1200,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 5,
                "storytelling": 5,
                "emotion": 5,
                "humor": 4,
                "question_usage": 4,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "시설 규모, 장비 종류, 편의시설, 위치, 운영시간 등을 입력하세요",
            "example_topics": ["센터 리뉴얼 안내", "최신 장비 소개", "샤워실 및 편의시설"],
        },
    ],

    IndustryType.EDUCATION: [
        {
            "id": "education_curriculum",
            "name": "커리큘럼 소개",
            "icon": "📚",
            "description": "교육 과정과 커리큘럼을 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 2000,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 7,
                "storytelling": 5,
                "emotion": 4,
                "humor": 3,
                "question_usage": 5,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "과정명, 대상, 수업 내용, 교재, 수업 방식, 수강료 등을 입력하세요",
            "example_topics": ["중등 수학 심화반", "코딩 입문 과정", "영어 회화 집중 과정"],
        },
        {
            "id": "education_study_guide",
            "name": "학습법 가이드",
            "icon": "💡",
            "description": "효과적인 학습 방법을 안내하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 7,
                "technical_depth": 6,
                "storytelling": 6,
                "emotion": 5,
                "humor": 4,
                "question_usage": 7,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "학습 방법, 대상 학년, 과목, 팁, 추천 교재 등을 입력하세요",
            "example_topics": ["수능 국어 공부법", "초등 영어 시작 가이드", "암기 효율 높이는 방법"],
        },
        {
            "id": "education_success_story",
            "name": "성적 향상 사례",
            "icon": "🏆",
            "description": "학생의 성적 향상 사례를 공유하는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "공감해결형",
                "target_length": 1500,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 5,
                "storytelling": 9,
                "emotion": 7,
                "humor": 3,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "학생 배경(익명), 초기 성적, 학습 과정, 결과, 소감 등을 입력하세요",
            "example_topics": ["수학 40점→90점 비결", "영어 1등급 달성기", "코딩 대회 수상 후기"],
        },
    ],

    IndustryType.REALESTATE: [
        {
            "id": "realestate_listing",
            "name": "매물 소개",
            "icon": "🏠",
            "description": "부동산 매물을 매력적으로 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 6,
                "storytelling": 5,
                "emotion": 4,
                "humor": 2,
                "question_usage": 4,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "매물 유형, 위치, 면적, 가격, 특징, 교통/학군 정보 등을 입력하세요",
            "example_topics": ["강남 역세권 오피스텔", "신축 아파트 분양 안내", "수익형 상가 매물"],
        },
        {
            "id": "realestate_area_analysis",
            "name": "지역 분석",
            "icon": "📊",
            "description": "특정 지역의 부동산 환경을 분석하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 2200,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 7,
                "friendliness": 5,
                "technical_depth": 8,
                "storytelling": 4,
                "emotion": 3,
                "humor": 2,
                "question_usage": 4,
                "metaphor_usage": 3,
                "sentence_length": 6,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": True,
                "search_intent_match": True,
            },
            "placeholder_content": "지역명, 개발 호재, 교통, 학군, 생활 인프라, 시세 추이 등을 입력하세요",
            "example_topics": ["마곡지구 투자 분석", "위례신도시 입주 가이드", "GTX 노선 주변 분석"],
        },
        {
            "id": "realestate_market_trend",
            "name": "시세 동향",
            "icon": "📈",
            "description": "부동산 시세 동향과 전망을 분석하는 글",
            "config": {
                "persuasion_level": 3,
                "framework": "정보전달형",
                "target_length": 2000,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 7,
                "friendliness": 5,
                "technical_depth": 8,
                "storytelling": 3,
                "emotion": 3,
                "humor": 2,
                "question_usage": 4,
                "metaphor_usage": 3,
                "sentence_length": 6,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": True,
                "search_intent_match": True,
            },
            "placeholder_content": "지역, 매물 유형, 현재 시세, 변동 추이, 전망 등을 입력하세요",
            "example_topics": ["서울 아파트 시세 동향", "전세 시장 전망", "상가 임대료 추이"],
        },
        {
            "id": "realestate_investment",
            "name": "투자 가이드",
            "icon": "💰",
            "description": "부동산 투자에 대한 가이드와 팁을 제공하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 2000,
                "writing_perspective": "3인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 7,
                "storytelling": 5,
                "emotion": 4,
                "humor": 2,
                "question_usage": 6,
                "metaphor_usage": 4,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": True,
                "multi_perspective": True,
                "search_intent_match": True,
            },
            "placeholder_content": "투자 유형, 초보 가이드, 세금, 수익률, 주의사항 등을 입력하세요",
            "example_topics": ["소액 부동산 투자 방법", "경매 입문 가이드", "임대수익률 계산법"],
        },
    ],

    IndustryType.OTHER: [
        {
            "id": "other_service",
            "name": "서비스 소개",
            "icon": "🛠️",
            "description": "제공하는 서비스를 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 1800,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 5,
                "friendliness": 7,
                "technical_depth": 5,
                "storytelling": 6,
                "emotion": 5,
                "humor": 4,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "서비스명, 특징, 장점, 대상 고객, 가격 등을 입력하세요",
            "example_topics": ["인테리어 서비스 소개", "출장 세차 서비스", "맞춤 의류 제작"],
        },
        {
            "id": "other_review",
            "name": "고객 후기",
            "icon": "⭐",
            "description": "고객 후기와 경험을 공유하는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "공감해결형",
                "target_length": 1500,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 4,
                "friendliness": 8,
                "technical_depth": 4,
                "storytelling": 9,
                "emotion": 8,
                "humor": 4,
                "question_usage": 5,
                "metaphor_usage": 5,
                "sentence_length": 4,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": False,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "이용 계기, 서비스 경험, 결과, 만족도 등을 입력하세요",
            "example_topics": ["이사 업체 이용 후기", "반려동물 미용 후기", "온라인 쇼핑 리뷰"],
        },
        {
            "id": "other_event",
            "name": "이벤트",
            "icon": "🎉",
            "description": "이벤트나 프로모션을 홍보하는 글",
            "config": {
                "persuasion_level": 5,
                "framework": "관심유도형",
                "target_length": 1000,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 3,
                "friendliness": 9,
                "technical_depth": 3,
                "storytelling": 5,
                "emotion": 7,
                "humor": 5,
                "question_usage": 6,
                "metaphor_usage": 5,
                "sentence_length": 3,
            },
            "seo_optimization": {
                "enabled": False,
                "experience_focus": False,
                "expertise": False,
                "originality": True,
                "timeliness": True,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": False,
            },
            "placeholder_content": "이벤트명, 기간, 혜택, 참여 방법 등을 입력하세요",
            "example_topics": ["오픈 기념 할인 이벤트", "리뷰 작성 사은품", "추천인 이벤트"],
        },
        {
            "id": "other_company_intro",
            "name": "업체 소개",
            "icon": "🏪",
            "description": "업체의 역사, 철학, 특장점을 소개하는 글",
            "config": {
                "persuasion_level": 4,
                "framework": "정보전달형",
                "target_length": 1500,
                "writing_perspective": "1인칭",
            },
            "writing_style": {
                "formality": 6,
                "friendliness": 6,
                "technical_depth": 5,
                "storytelling": 7,
                "emotion": 5,
                "humor": 3,
                "question_usage": 4,
                "metaphor_usage": 5,
                "sentence_length": 5,
            },
            "seo_optimization": {
                "enabled": True,
                "experience_focus": True,
                "expertise": True,
                "originality": True,
                "timeliness": False,
                "topic_concentration": True,
                "trustworthiness": True,
                "source_authority": False,
                "multi_perspective": False,
                "search_intent_match": True,
            },
            "placeholder_content": "업체 이름, 설립 배경, 핵심 가치, 대표 상품/서비스 등을 입력하세요",
            "example_topics": ["창업 스토리", "10년 전통 업체 소개", "우리 가게의 철학"],
        },
    ],
}


# ==================== 업종별 프로필 기본값 ====================

INDUSTRY_PROFILE_DEFAULTS: Dict[IndustryType, Dict[str, Any]] = {
    IndustryType.MEDICAL: {
        "writing_style": {
            "formality": 7,
            "friendliness": 5,
            "technical_depth": 7,
            "storytelling": 5,
            "emotion": 4,
        },
        "target_audience": {
            "age_range": "30-60",
            "gender": "",
            "recommended_concerns": ["건강검진", "만성질환", "시술상담", "통증관리", "다이어트"],
        },
        "recommended_phrases": [
            "환자분들께 말씀드리는데요",
            "진료실에서 자주 듣는 질문이에요",
            "의학적으로 말씀드리면",
            "제 경험상",
            "많은 분들이 궁금해하시는",
        ],
        "recommended_structure": "story_problem_solution",
    },
    IndustryType.LEGAL: {
        "writing_style": {
            "formality": 7,
            "friendliness": 5,
            "technical_depth": 7,
            "storytelling": 6,
            "emotion": 3,
        },
        "target_audience": {
            "age_range": "30-55",
            "gender": "",
            "recommended_concerns": ["이혼상담", "부동산분쟁", "형사사건", "채권추심", "노동분쟁"],
        },
        "recommended_phrases": [
            "법적으로 말씀드리면",
            "실제 상담에서 많이 받는 질문이에요",
            "판례를 살펴보면",
            "주의하셔야 할 점은",
            "법률 전문가의 조언이 필요한 경우",
        ],
        "recommended_structure": "story_problem_solution",
    },
    IndustryType.RESTAURANT: {
        "writing_style": {
            "formality": 3,
            "friendliness": 9,
            "technical_depth": 3,
            "storytelling": 8,
            "emotion": 8,
        },
        "target_audience": {
            "age_range": "20-40",
            "gender": "",
            "recommended_concerns": ["맛집탐방", "데이트코스", "가족외식", "모임장소", "배달맛집"],
        },
        "recommended_phrases": [
            "오늘 소개할 메뉴는요",
            "이 맛을 놓치면 후회해요",
            "사장님이 직접 추천하는",
            "단골분들이 꼭 시키는",
            "여기 진짜 맛집이에요",
        ],
        "recommended_structure": "aida",
    },
    IndustryType.BEAUTY: {
        "writing_style": {
            "formality": 4,
            "friendliness": 8,
            "technical_depth": 5,
            "storytelling": 7,
            "emotion": 7,
        },
        "target_audience": {
            "age_range": "20-40",
            "gender": "female",
            "recommended_concerns": ["피부관리", "헤어스타일", "네일아트", "안티에이징", "트렌드"],
        },
        "recommended_phrases": [
            "요즘 핫한 트렌드예요",
            "많은 고객님들이 만족하셨어요",
            "전후 사진 보시면 깜짝 놀라실 거예요",
            "상담을 통해 맞춤 제안 드려요",
            "꾸준한 관리가 중요해요",
        ],
        "recommended_structure": "aida",
    },
    IndustryType.FITNESS: {
        "writing_style": {
            "formality": 4,
            "friendliness": 8,
            "technical_depth": 6,
            "storytelling": 7,
            "emotion": 6,
        },
        "target_audience": {
            "age_range": "20-45",
            "gender": "",
            "recommended_concerns": ["다이어트", "근력강화", "체형교정", "건강관리", "스트레스해소"],
        },
        "recommended_phrases": [
            "오늘도 운동하셨나요?",
            "초보자도 쉽게 따라할 수 있어요",
            "꾸준함이 가장 중요합니다",
            "회원님의 변화가 증명합니다",
            "목표를 향해 함께 달려봐요",
        ],
        "recommended_structure": "pas",
    },
    IndustryType.EDUCATION: {
        "writing_style": {
            "formality": 6,
            "friendliness": 7,
            "technical_depth": 6,
            "storytelling": 6,
            "emotion": 5,
        },
        "target_audience": {
            "age_range": "30-50",
            "gender": "",
            "recommended_concerns": ["성적향상", "입시준비", "학습습관", "자기주도학습", "진로상담"],
        },
        "recommended_phrases": [
            "공부 잘하는 학생들의 비밀",
            "학부모님들이 가장 궁금해하시는",
            "성적 향상의 핵심은",
            "맞춤 학습 설계로",
            "실제 수강생의 후기에요",
        ],
        "recommended_structure": "story_problem_solution",
    },
    IndustryType.REALESTATE: {
        "writing_style": {
            "formality": 7,
            "friendliness": 5,
            "technical_depth": 7,
            "storytelling": 4,
            "emotion": 3,
        },
        "target_audience": {
            "age_range": "30-55",
            "gender": "",
            "recommended_concerns": ["내집마련", "투자분석", "시세정보", "전세상담", "경매정보"],
        },
        "recommended_phrases": [
            "현장을 직접 다녀왔습니다",
            "시세 데이터로 분석해보면",
            "투자 관점에서 주목할 점은",
            "실거주 관점에서 보면",
            "전문 중개사의 의견으로는",
        ],
        "recommended_structure": "story_problem_solution",
    },
    IndustryType.OTHER: {
        "writing_style": {
            "formality": 5,
            "friendliness": 7,
            "technical_depth": 5,
            "storytelling": 6,
            "emotion": 5,
        },
        "target_audience": {
            "age_range": "25-50",
            "gender": "",
            "recommended_concerns": ["서비스문의", "가격비교", "후기확인", "이벤트정보", "업체비교"],
        },
        "recommended_phrases": [
            "저희를 찾아주신 분들께",
            "고객님들의 후기를 소개합니다",
            "직접 경험해보세요",
            "지금 바로 문의하세요",
            "정성을 다해 모시겠습니다",
        ],
        "recommended_structure": "aida",
    },
}


def get_industry_templates(industry_type: IndustryType) -> List[Dict[str, Any]]:
    """업종별 글쓰기 템플릿 반환"""
    return INDUSTRY_WRITING_TEMPLATES.get(industry_type, INDUSTRY_WRITING_TEMPLATES[IndustryType.OTHER])


def get_industry_profile_defaults(industry_type: IndustryType) -> Dict[str, Any]:
    """업종별 프로필 기본값 반환"""
    return INDUSTRY_PROFILE_DEFAULTS.get(industry_type, INDUSTRY_PROFILE_DEFAULTS[IndustryType.OTHER])
